version: "3"

services:
  webapi:
    image: simpleapi:latest
    build:
      context: Simple.Api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"